name: build-jit

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - 'plugin/**'
      - 'build/**'

jobs:
  build:
    runs-on: windows-2022   # 2019 aposentado; 2022 funciona

    steps:
      - name: Checkout (com submódulos)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild (VS2022)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)'   # força VS 2022

      - name: Configurar solução (gera .sln / .vcxproj)
        shell: cmd
        run: build\visual-studio\configure.bat

      - name: Encontrar solução gerada
        shell: pwsh
        run: |
          $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
          if (!$sln) { throw "Nenhuma .sln gerada" }
          "SLN=$($sln.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      # Tenta v142 (se a imagem tiver instalado); se falhar, tenta v143
      - name: Compilar Release|Win32 (tenta v142 -> v143)
        shell: cmd
        run: |
          msbuild "%SLN%" /m /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v142 /v:m ^
          || msbuild "%SLN%" /m /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /v:m

      - name: Listar DLLs (debug)
        shell: pwsh
        run: Get-ChildItem -Recurse -Filter jit.dll | % { $_.FullName }

      - name: Publicar jit.dll
        uses: actions/upload-artifact@v4
        with:
          name: jit-dll
          path: |
            **\Release\jit.dll
            **\jit.dll
