name: build-jit

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.h'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'build/**'

jobs:
  build:
    runs-on: windows-2022   # estável hoje

    steps:
      - name: Checkout (com submódulos)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Gera arquivos de build para o VS 2022 (Win32 = 32-bit)
      - name: Configure (CMake VS2022 Win32)
        shell: bash
        run: cmake -S . -B build_vs -G "Visual Studio 17 2022" -A Win32

      - name: Build Release
        shell: bash
        run: cmake --build build_vs --config Release --parallel

      - name: Coletar DLL resultante
        shell: pwsh
        run: |
          $dll = Get-ChildItem -Path build_vs -Recurse -Filter jit.dll | Select-Object -First 1
          if (!$dll) { throw "jit.dll não encontrado em build_vs/*/Release" }
          "ARTIFACT=$($dll.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: jit-dll
          path: ${{ env.ARTIFACT }}
