name: build-jit

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - 'plugin/**'
      - 'build/**'

jobs:
  build:
    runs-on: windows-2019   # VS2019 (v142) – mais compatível com o JIT antigo

    steps:
      - name: Checkout (com submódulos)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild (VS2019)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[16.0,17.0)'   # força MSBuild do VS2019

      - name: Configurar solução (gera .sln/.vcxproj)
        shell: cmd
        run: build\visual-studio\configure.bat

      - name: Encontrar solução gerada
        shell: pwsh
        run: |
          $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
          if (!$sln) { throw "Nenhuma .sln gerada" }
          "SLN=$($sln.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Compilar Release|Win32 (toolset v142)
        shell: cmd
        run: msbuild "%SLN%" /m /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v142 /v:m

      - name: Listar saídas (debug)
        shell: cmd
        run: dir /s /b *.dll

      - name: Publicar jit.dll
        uses: actions/upload-artifact@v4
        with:
          name: jit-dll
          path: |
            **\Release\jit.dll
            **\jit.dll
